{
    section: 'Climate',
    subsection: '',
    title: 'Climate Change Poses Threats to Children’s Health Worldwide',
    abstract: 'A study from the Lancet points to infectious diseases, worsening air pollution, rising temperatures and even malnutrition as threats to child health as the climate changes. ',
    url: 'https://www.nytimes.com/2019/11/13/climate/climate-change-child-health.html',
    byline: 'By KENDRA PIERRE-LOUIS',
    item_type: 'Article',
    updated_date: '2019-11-13T19:36:22-05:00',
    created_date: '2019-11-13T18:30:08-05:00',
    published_date: '2019-11-13T18:30:08-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [],
    geo_facet: [],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2QcyPns'
  },
  {
    section: 'Science',
    subsection: '',
    title: 'Still the Undisputed Champs of Mammalian Migrations',
    abstract: 'Scientists measured distances covered to compile a Top 5 list of ultramarathon runners of land mammals.',
    url: 'https://www.nytimes.com/2019/11/13/science/land-mammal-migrations.html',
    byline: 'By CARA GIAIMO',
    item_type: 'Article',
    updated_date: '2019-11-18T14:10:34-05:00',
    created_date: '2019-11-13T14:33:02-05:00',
    published_date: '2019-11-13T14:33:02-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [Array],
    geo_facet: [Array],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2KiDZKU'
  },
  {
    section: 'Health',
    subsection: '',
    title: 'New York Identifies Hospitals and Nursing Homes With Deadly Fungus',
    abstract: 'The policy change, for the virulent drug-resistant germ Candida auris, came as the C.D.C. reported that more people are dying of drug-resistant infections than it previously estimated.',
    url: 'https://www.nytimes.com/2019/11/13/health/candida-auris-resistant-hospitals.html',
    byline: 'By MATT RICHTEL and ANDREW JACOBS',
    item_type: 'Article',
    updated_date: '2019-11-14T03:04:28-05:00',
    created_date: '2019-11-13T13:14:03-05:00',
    published_date: '2019-11-13T13:14:03-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [],
    geo_facet: [Array],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2KiHxMZ'
  },
  {
    section: 'U.S.',
    subsection: '',
    title: '3 Cows Swept Out to Sea by Hurricane Dorian Are Found Alive',
    abstract: 'The cows, believed to have been carried out to sea when the storm hit North Carolina, have been spotted hanging out on the Outer Banks.',
    url: 'https://www.nytimes.com/2019/11/13/us/hurricane-dorian-cows.html',
    byline: 'By JOHNNY DIAZ and AIMEE ORTIZ',
    item_type: 'Article',
    updated_date: '2019-11-13T15:42:08-05:00',
    created_date: '2019-11-13T12:58:47-05:00',
    published_date: '2019-11-13T12:58:47-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [],
    geo_facet: [Array],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2KioId2'
  },
  {
    section: 'New York',
    subsection: '',
    title: 'Where Wild Turkeys Are So Bold They Knock on the Door for Food',
    abstract: 'Birds behaving badly are causing a ruckus in Toms River, N.J.',
    url: 'https://www.nytimes.com/2019/11/13/nyregion/turkeys-toms-river.html',
    byline: 'By TRACEY TULLY',
    item_type: 'Article',
    updated_date: '2019-11-14T16:13:52-05:00',
    created_date: '2019-11-13T11:20:10-05:00',
    published_date: '2019-11-13T11:20:10-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [Array],
    geo_facet: [Array],
    multimedia: [Array],
    short_url: 'https://nyti.ms/32IBM1y'
  },
  {
    section: 'Science',
    subsection: '',
    title: 'How to Peer Through a Wormhole',
    abstract: 'Theoretically, the universe may be riddled with tunnels through space and time. Two scientists have now proposed a way to detect the existence of a cosmic escape hatch.',
    url: 'https://www.nytimes.com/2019/11/13/science/wormholes-physics-astronomy-cosmos.html',
    byline: 'By DENNIS OVERBYE',
    item_type: 'Article',
    updated_date: '2019-11-13T11:06:43-05:00',
    created_date: '2019-11-13T10:00:10-05:00',
    published_date: '2019-11-13T10:00:10-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [],
    per_facet: [Array],
    geo_facet: [],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2O7rfb4'
  },
  {
    section: 'Arts',
    subsection: 'Art & Design',
    title: 'Penn Museum Redesign Aims Beyond Academics',
    abstract: 'Hundreds of objects from a collection of almost one million artifacts will go on public display for the first time when new galleries open this week.',
    url: 'https://www.nytimes.com/2019/11/13/arts/design/penn-museum-redesign.html',
    byline: 'By JON HURDLE',
    item_type: 'Article',
    updated_date: '2019-11-13T14:52:47-05:00',
    created_date: '2019-11-13T09:48:23-05:00',
    published_date: '2019-11-13T09:48:23-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [],
    geo_facet: [Array],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2NHfJUO'
  },
  {
    section: 'Science',
    subsection: 'Space & Cosmos',
    title: 'NASA Renames Object After Uproar Over Old Name’s Nazi Connotations',
    abstract: 'Scientists said an object four billion miles from Earth would be given a Native American name: Arrokoth. Its previous, informal name, Ultima Thule, had links to the Third Reich.',
    url: 'https://www.nytimes.com/2019/11/13/science/space/nasa-arrokoth-kuiper-belt.html',
    byline: 'By LIAM STACK',
    item_type: 'Article',
    updated_date: '2019-11-13T14:34:38-05:00',
    created_date: '2019-11-13T05:00:18-05:00',
    published_date: '2019-11-13T05:00:18-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [],
    geo_facet: [],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2NHnYjy'
  },
  {
    section: 'Travel',
    subsection: '',
    title: 'Looking to Scientists to Expand Eco-Tourism Efforts',
    abstract: 'Hotels, lodges and resorts are bringing in scientists to conduct serious academic inquiries while also offering nature tours, workshops and classes for guests.',
    url: 'https://www.nytimes.com/2019/11/13/travel/ecotourism-scientists.html',
    byline: 'By ABBY ELLIN',
    item_type: 'Article',
    updated_date: '2019-11-13T05:00:09-05:00',
    created_date: '2019-11-13T05:00:09-05:00',
    published_date: '2019-11-13T05:00:09-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [],
    geo_facet: [Array],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2Kco9Bt'
  },
  {
    section: 'Climate',
    subsection: '',
    title: '5 Global Trends Shaping Our Climate Future',
    abstract: "Here's how the next 20 years are shaping up in terms of energy, and what it means for global warming.",
    url: 'https://www.nytimes.com/2019/11/12/climate/energy-trends-climate-change.html',
    byline: 'By BRAD PLUMER',
    item_type: 'Article',
    updated_date: '2019-11-13T09:17:45-05:00',
    created_date: '2019-11-12T19:00:11-05:00',
    published_date: '2019-11-12T19:00:11-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [Array],
    per_facet: [],
    geo_facet: [Array],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2pXZbir'
  },
  {
    section: 'Climate',
    subsection: '',
    title: 'Greta Thunberg Sets Sail, Again, After Climate Talks Relocate',
    abstract: 'Ms. Thunberg, who doesn’t fly, found herself suddenly needing a ride across the Atlantic  when United Nations climate talks were moved on short notice.',
    url: 'https://www.nytimes.com/2019/11/12/climate/greta-thunberg-return-europe.html',
    byline: 'By SOMINI SENGUPTA',
    item_type: 'Article',
    updated_date: '2019-11-13T16:27:29-05:00',
    created_date: '2019-11-12T18:00:09-05:00',
    published_date: '2019-11-12T18:00:09-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [Array],
    org_facet: [],
    per_facet: [Array],
    geo_facet: [],
    multimedia: [Array],
    short_url: 'https://nyti.ms/2NFyOqs'
  }
]
}